name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

permissions:
  issues: write

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'neggo' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install comfy-cli
        run: pip install comfy-cli

      - name: Publish Custom Node via comfy-cli
        env:
          COMFY_REGISTRY_API_KEY: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        run: |
          # 対話プロンプトをスキップして実行
          comfy node publish --skip-prompt
